ALTER TABLE topic_ratings ADD COLUMN IF NOT EXISTS rd DOUBLE PRECISION DEFAULT 350.0;
ALTER TABLE topic_ratings ADD COLUMN IF NOT EXISTS volatility DOUBLE PRECISION DEFAULT 0.06;
ALTER TABLE topic_ratings ADD COLUMN IF NOT EXISTS conservative_rating DOUBLE PRECISION DEFAULT 800.0;
ALTER TABLE topic_ratings ADD COLUMN IF NOT EXISTS last_practiced_at TIMESTAMP;
